### ISSUE TITLE
Blade template not resolved

### ISSUE THREAD

**Issue by shaffe-fr** [spatie/laravel-ignition#104]
Hello,

When an exception is thrown inside a view, the compiled cache view is shown instead of the initial blade template.

Is this the intended behaviour? 

![image](https://user-images.githubusercontent.com/3834222/181453133-daec2589-812c-4413-99f5-0a389355cff7.png)

Thanks,
Karel

**Comment by jcmcclorey** [comment]
I have the same question, the previous setup in Laravel used the regular blade view and I would like to get that functionality back. It's a real pain to try to match up the compiled view with the blade view

**Comment by SocolaDaiCa** [comment]
#132

**Comment by SocolaDaiCa** [comment]
@shaffe-fr @VincentVanWijk  Fixed https://github.com/spatie/laravel-ignition/releases/tag/1.6.4

**Comment by Vincent-avant** [comment]
@SocolaDaiCa Perhaps out of scope for this issue, but the collapse vendor frames button does not work yet. I was hoping it had something to do with the paths that were fixed with your pull request

**Comment by SocolaDaiCa** [comment]
@Vincent-avant what is `collapse vendor`. Could you explain It.

**Comment by Vincent-avant** [comment]
@SocolaDaiCa 
As you can see on the screenshot at the top of this issue, there is a button on the top-left named "collapse vendor frames".

It collapses the stack trace on the left, to filter out the method calls of the framework itself, and only shows you 'your' files, if I understand it correctly.

You can see it working in this video on Freek van der Herten's channel :
https://www.youtube.com/watch?v=LEY0N0Bteew&t=739s

You can see a dropdown in the video that says "7 vendor frames" and "44 vendor frames". 
This is what is currently not working on windows, the button does not collapse the stack trace.

**Comment by shaffe-fr** [comment]
I have the same issue on Windows. You can maybe create a dedicated issue @Vincent-avant ?
