### ISSUE TITLE
Uncaught TypeError: window.ignite is not a function

### ISSUE THREAD

**Issue by zanysoft** [spatie/laravel-ignition#107]
### I am facing following error on localhost:

GET http://citylocal101.qrg/account 500 (Internal Server Error)
Uncaught SyntaxError: Invalid regular expression: /,"&lt;").replace(/: Unmatched ')' (at account:230:72552)
Uncaught TypeError: window.ignite is not a function    at account:239:30
Uncaught ReferenceError: Ignition is not defined    at account:242:5

![Untitled](https://user-images.githubusercontent.com/2682072/186213698-da1a23e7-83f0-4567-9110-1415aa0ce53f.jpg)

**Comment by AlexVanderbist** [comment]
Hi there! Can you try opening this page in Incognito mode (or without any extensions enabled)? It seems like there's some additional JavaScript injected into the Ignition page that isn't there by default.

**Comment by fh32000** [comment]
لقد ظهر معي نفس المشكله عند اضافه المكتبه 
```
         -composer.js-
        "renatomarinho/laravel-page-speed": "^2.1",
        
        ---Kernal.php--
        //        \RenatoMarinho\LaravelPageSpeed\Middleware\InlineCss::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\ElideAttributes::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\InsertDNSPrefetch::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\RemoveComments::class,
//        \RenatoMarinho\LaravelPageSpeed\Middleware\TrimUrls::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\RemoveQuotes::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class,

```

لذالك قمت بإزالة 


         \RenatoMarinho\LaravelPageSpeed\Middleware\RemoveComments::class,
        \RenatoMarinho\LaravelPageSpeed\Middleware\CollapseWhitespace::class,

**Comment by CodeTechNL** [comment]
I've had the same issue with 1.6. After downgrading to 1.3.1 it worked again. There is a syntax error in the JavaScript file which might cause the problem.

**Comment by mikerockett** [comment]
Just bumped into this as well. I had actually removed the package to see what would happen with exceptions. Re-adding it somehow caused the issue.

**Comment by CodeTechNL** [comment]
> Just bumped into this as well. I had actually removed the package to see what would happen with exceptions. Re-adding it somehow caused the issue.

Downgrade to another version does the trick for now

**Comment by mikerockett** [comment]
Apologies, turns out a middleware was interfering with the output.

**Comment by Levivb** [comment]
Leaving this here: https://github.com/spatie/ignition/issues/300
