### ISSUE TITLE
Current release has still a transitive dependency to the abandoned swift mailer package

### ISSUE THREAD

**Issue by cloudlog** [spatie/laravel-ignition#123]
The last release 1.6.1 does still have a transitive dependency to the abandoned swift mailer package via the monolog package ^2.3.

https://packagist.org/packages/spatie/laravel-ignition

There is a new version (3.x) of monolog available that does not have the swift mailer dependency anymore.

https://packagist.org/packages/monolog/monolog#3.2.0

Maybe update to it?

**Comment by freekmurze** [comment]
We're following Laravel here. They also require monolog v2: https://github.com/laravel/framework/blob/4598d014212f18d766f7a4bb5c109820bd8b823d/composer.json#L28

We'll update our dependency when Laravel updates it.
