### ISSUE TITLE
Failed to support php 8.2 as composer failed

### ISSUE THREAD

**Issue by qiulang** [spatie/laravel-ignition#133]
This is my composer.json and it failed.

    "require": {
        "php": "^8.2",
        "clue/socket-raw": "^1.3",
        "fideloper/proxy": "^4.4",
        "fruitcake/laravel-cors": "^2.0",
        "gregwar/captcha": "1.*",
        "guzzlehttp/guzzle": "^7.0.1",
        "itsgoingd/clockwork": "^5.1",
        "jacobcyl/ali-oss-storage": "^2.0",
        "james-heinrich/getid3": "^1.9",
        "laravel/framework": "^9.33",
        "laravel/horizon": "^5.7",
        "laravel/tinker": "^2.5",
        "php-curl-class/php-curl-class": "^8.6",
    },
    "require-dev": {
        "spatie/laravel-ignition":"^1.6.4",
        "fakerphp/faker": "^1.21.0",
        "laravel/sail": "^1.18.1",
        "mockery/mockery": "^1.5.1",
        "nunomaduro/collision": "^6.4",
        "phpunit/phpunit": "^9.5.28"
    },

Following are the composer error message,

> spatie/laravel-ignition 1.6.4 requires spatie/ignition ^1.4.1 -> found spatie/ignition[dev-dependabot/github_actions/ramsey/composer-install-2, dev-dependabot/github_actions/actions/setup-node-3, dev-dependabot/github_actions/actions/cache-3, dev-dependabot/github_actions/actions/checkout-3, dev-main, dev-old, dev-l10, dev-shift-52829, 0.0.1, ..., 0.0.8, 1.0.0, ..., 1.3.1] but it does not match the constraint.

Removing "spatie/laravel-ignition" from "require-dev" or using php 8.1.7 both work fine. So I think "spatie/laravel-ignition" doesn't support 8.2 yet, even though I saw https://github.com/spatie/laravel-ignition/pull/128 said "Add PHP 8.2 Support"

**Comment by freekmurze** [comment]
Our tests prove that PHP 8.2 support is working: https://github.com/spatie/laravel-ignition/actions/runs/3832393646/jobs/6522650060

**Comment by qiulang** [comment]
But I have given you a failed case. Why the rush to close it immediately without even looking into it ?

**Comment by NicoHaase** [comment]
@qiulang you should at least share the information that you are using an unofficial mirror, as provided in https://stackoverflow.com/questions/75133154/php-8-2-laravel-9-failed-with-composer-error-that-cron-expression-does-not-mat

**Comment by qiulang** [comment]
@NicoHaase as a matter of fact after I discussed with you I remove the mirror setting from my composer.json but the result was the same. composer complained the same error.

**Comment by qiulang** [comment]
And that is NOT unofficial mirror, that is one of the official mirror in China as https://packagist.org/mirrors suggest!

**Comment by freekmurze** [comment]
> But I have given you a failed case. Why the rush to close it immediately without even looking into it ?

I've tried installing it in fresh project using Laravel 8.2 and it just worked.
