### ISSUE TITLE
Variable dumping can lead to gigantic html pages/OOM

### ISSUE THREAD

**Issue by imerr** [spatie/laravel-ignition#137]
(I hope this is the right place, if not please point me where to take this)

I've just been tracking down a seemingly random "out of memory" (memory exhaustion or whatever term is preferred in php land) we've been experiencing during development.

It would show up whenever another error/exception triggered the laravel ignition error page (which is sweet btw! good job there), but only sometimes

After some debugging and (at first) blaming the laravel-debugbar package (it did more than double the page size), it turns out a models passed to our views sometimes have a binary field filled out that can have a ~800kb blob in it.
This then gets multiplied, via encoding and printing to html a handful of times resulting in a ~45MB .html file (or 100MB with the aforementioned debug bar active) or an out of memory exception

I've had a quick look at the code and it should be possible to override `dumpString` in https://github.com/spatie/laravel-ignition/blob/efff1c5b6f25c066cd4890fda2ca883dafcecee6/src/Recorders/DumpRecorder/HtmlDumper.php#L9 to give string dumping a configurable safety limit by simply truncating it past the limit (mabe 50kb would be a reasonable default?)

**Comment by freekmurze** [comment]
Feel free to PR improvements around this! 👍
