### ISSUE TITLE
During a ddd() or even a dd() all data is already extended and cannot be folded back

### ISSUE THREAD

**Issue by MagnusDot** [spatie/laravel-ignition#148]
After upgrading to laravel 10, this bug happens on all the data dumps, maybe it's my fault or I've done something wrong, so I'm wondering...

I have the impression that the classes: 'sf-dump-compact' 'sf-dump-toggle' no longer have any effect

here's an example, without my having touched anything: 
![image](https://github.com/spatie/laravel-ignition/assets/39904918/9e5cef16-30eb-4a92-82fd-88f25e6cd496)

**Comment by daaner** [comment]
Some problem

**Comment by daaner** [comment]
Copy issue in https://github.com/symfony/var-dumper/pulls

**Comment by daaner** [comment]
> After upgrading to laravel 10, this bug happens on all the data dumps, maybe it's my fault or I've done something wrong, so I'm wondering...
> 
> I have the impression that the classes: 'sf-dump-compact' 'sf-dump-toggle' no longer have any effect
> 
> here's an example, without my having touched anything: ![image](https://user-images.githubusercontent.com/39904918/245184419-9e5cef16-30eb-4a92-82fd-88f25e6cd496.png)

Copy issue in https://github.com/symfony/var-dumper/pulls
