### ISSUE TITLE
Mistake in configuration file comments

### ISSUE THREAD

**Issue by TheAndrey** [spatie/laravel-ignition#162]
I found that both parameters `solution_providers` and `ignored_solution_providers` of the configuration file have the same description: «providers that shouldn't be loaded». This is misleading.

https://github.com/spatie/laravel-ignition/blob/main/config/ignition.php

**Comment by flap152** [comment]
Submitted PR to fix this https://github.com/spatie/laravel-ignition/pull/172
(noticed open issue afterwards)
