### ISSUE TITLE
Ignition Settings Dropdown

### ISSUE THREAD

**Issue by Jxckaroo** [spatie/laravel-ignition#17]
Hey - I love the new ignition, it is awesome!

Just one thing I spotted though, on Chrome, in dark mode, when selecting an IDE in the ignition settings, the text colour seems to be the same as the dropdown background making it a bit hard to see the other options.

![image](https://user-images.githubusercontent.com/24681027/150034934-b761955a-b8f7-428d-8ee0-7f747cbe7d47.png)

**Comment by freekmurze** [comment]
Thanks for reporting, we'll fix this soon!

**Comment by Jxckaroo** [comment]
> Thanks for reporting, we'll fix this soon!

No worries! :) - really really great job with this.
