### ISSUE TITLE
HtmlDumper::$dumpHeader is not compatible with symfony's $dumpHeader.

### ISSUE THREAD

**Issue by nshiro** [spatie/laravel-ignition#175]
Symfony added types to public and protected properties in v7.0.2.
https://github.com/symfony/var-dumper/commit/29640583bb9e980054934f87b4aed049fe8531a2#diff-3ecbc1b7f995db6056ace83cf869b5440d6877e462c768a35bcb6acf77df6d0bR62

And we now get this error message with symfony v7.
`Type of Spatie\LaravelIgnition\Recorders\DumpRecorder\HtmlDumper::$dumpHeader must be ?string (as in class Symfony\Component\VarDumper\Dumper\HtmlDumper)`

I'm not sure what the best solution is.
So I just submitted the issue.

**Comment by mickedplay** [comment]
+1

**Comment by freekmurze** [comment]
This is fixed in the latest release.
