### ISSUE TITLE
Type error in package discovery

### ISSUE THREAD

**Issue by shiftydevr** [spatie/laravel-ignition#18]
Laravel 8.80.0  with PHP 8.0.14.
Manually deleted "bootstrap\cache\packages.php" because it was still trying to find facade\ignition.

Very excited to see new Ignition, but it didn't install:
Last part of composer update after changing composer.json:
        "spatie/laravel-ignition": "^1.0",

  - Installing spatie/backtrace (1.2.1): Extracting archive
  - Installing spatie/flare-client-php (1.0.0): Extracting archive
  - Installing spatie/ignition (1.0.1): Extracting archive
  - Installing spatie/laravel-ignition (1.0.0): Extracting archive
C:\inetpub\TSMS> @php artisan vendor:publish --tag=laravel-assets --ansi

   TypeError

  Spatie\LaravelIgnition\Recorders\QueryRecorder\QueryRecorder::__construct(): Argument #2 ($reportBindings) must be of type bool, null given, called in C:\inetpub\TSMS\vendor\spatie\laravel-ignition\src\IgnitionServiceProvider.php on line 162

  at C:\inetpub\TSMS\vendor\spatie\laravel-ignition\src\Recorders\QueryRecorder\QueryRecorder.php:19
     15▕     protected bool $reportBindings = true;
     16▕
     17▕     protected ?int $maxQueries;
     18▕
  ➜  19▕     public function __construct(
     20▕         Application $app,
     21▕         bool $reportBindings = true,
     22▕         ?int $maxQueries = null
     23▕     ) {

  1   C:\inetpub\TSMS\vendor\spatie\laravel-ignition\src\IgnitionServiceProvider.php:162
      Spatie\LaravelIgnition\Recorders\QueryRecorder\QueryRecorder::__construct(Object(Illuminate\Foundation\Application))

  2   C:\inetpub\TSMS\vendor\laravel\framework\src\Illuminate\Container\Container.php:873
      Spatie\LaravelIgnition\IgnitionServiceProvider::Spatie\LaravelIgnition\{closure}(Object(Illuminate\Foundation\Application), [])

**Comment by freekmurze** [comment]
Thanks for reporting. It's difficult to recreate this. Could you create a minimal Laravel app that demonstrates this problem?

**Comment by shiftydevr** [comment]
I created a basic Laravel app from scratch and it worked to require laravel-ignition into that app.
I noticed there is a minor version update, tried the failing app and it still has the exact same error message as reported.

The Laravel app that is failing is fairly simple but was SHIFTed from Lumen to Laravel, don't know if that's relevant.
The rest is my handy work. I understand the difference between 'working' which it does, and being 'right' which it well may not be.
It's in a private repository on github where it was SHIFTed. I could give you access to have a look with a secure way to provide access.

**Comment by KostKostY1** [comment]
Any news on this one? 
Started failing today after updating to laravel 9 and spatie-ignition to 1.

Works fine locally but fails on my azure app service for some unknown reason i cant really understand.
 "laravel/framework": "^9.0",
"spatie/laravel-ignition": "^1.0",

Error log :
`[2022-03-02 10:18:42] production.ERROR: Spatie\LaravelIgnition\Recorders\QueryRecorder\QueryRecorder::__construct(): Argument #2 ($reportBindings) must be of type bool, null given, called in /home/site/wwwroot/vendor/spatie/laravel-ignition/src/IgnitionServiceProvider.php on line 164 {"exception":"[object] (TypeError(code: 0): Spatie\\LaravelIgnition\\Recorders\\QueryRecorder\\QueryRecorder::__construct(): Argument #2 ($reportBindings) must be of type bool, null given, called in /home/site/wwwroot/vendor/spatie/laravel-ignition/src/IgnitionServiceProvider.php on line 164 at /home/site/wwwroot/vendor/spatie/laravel-ignition/src/Recorders/QueryRecorder/QueryRecorder.php:19)`

**Comment by freekmurze** [comment]
Did you run `php artisan config:clear`?

**Comment by KostKostY1** [comment]
Tried it locally and works fine. On the server i get the same error again.
![image](https://user-images.githubusercontent.com/78410794/156352544-9cf18716-9a99-4a44-9e9f-7a224a05a2ac.png)

**Comment by freekmurze** [comment]
> Tried it locally and works fine. On the server i get the same error again.

This makes me think that you didn't clear all the caches on your server.

**Comment by KostKostY1** [comment]
Well..i can't clear them..i get the error....I can't really offer any more in the discussion...im kinda lost.
 It's 2 days work so ill start over and if the error persists ill inform you

**Comment by JvdK** [comment]
Hi, I had the same problem as described in the issue after an upgrade to Laravel 9 on an Azure app service. After trying to remove and reinstalling ignition using composer, I wasn't able to run `artisan config:clear` anymore. 

```
> php artisan config:clear

   TypeError 

  Spatie\Ignition\Config\IgnitionConfig::merge(): Argument #1 ($options) must be of type array, null given, called in /home/site/wwwroot/vendor/spatie/laravel-ignition/src/IgnitionServiceProvider.php on line 134
```

I fixed this by manually removing `bootstrap/cache/config.php` and running `artisan config:cache`

**Comment by AlexVanderbist** [comment]
Hi @JvdK, thanks for the in-depth explanation. I've made sure that the `$options` will always default to an empty array now, this should fix the issues you were having.

@KostKostY1 are you still experiencing this issue? I'll tag a bugfix release in less than an hour that'll fix `php artisan config:clear`. Sorry for the inconvenience this might've caused.
