### ISSUE TITLE
Ignition default config outside of appdir

### ISSUE THREAD

**Issue by dianfishekqi** [spatie/laravel-ignition#19]
Hello there,

After installing ignition, I stumbled upon an open_basedir restriction which triggers because ignition uses the home directory in Linux to store the default config (I assume to share the configs of different projects?), can we add an option to overwrite this behavior via config or keep the config somewhere inside the app directory?

I assume most people aren't comfortable loosening their open_dir restrictions.

![image](https://user-images.githubusercontent.com/4225509/150183660-6a43b5db-24a5-4e85-b085-ecff9c62d775.png)

**Comment by freekmurze** [comment]
Seems like you are using facade/ignition. Best to open an issue at that repo 👍

**Comment by dianfishekqi** [comment]
hello @freekmurze, as you can see i'm using `spatie/ignition`
![image](https://user-images.githubusercontent.com/4225509/150206104-47ef1948-6533-4102-ad45-100baf2334e1.png)
