### ISSUE TITLE
output from Symfony VarDumper's dump() is not shown

### ISSUE THREAD

**Issue by joachim-n** [spatie/laravel-ignition#194]
With PHP's built-in error page, or with XDebug's, the output from a call to dump() is shown above the error message and backtrace.

With Ignition however, it's not visible at all.

**Comment by rubenvanassche** [comment]
Have you taken a look at the bottom of the page?

<img width="1405" alt="screenshot 5" src="https://github.com/spatie/laravel-ignition/assets/619804/8c8bee1f-5558-4cee-a251-98e60e1bb81f">

**Comment by joachim-n** [comment]
Ah, I've got version 1.14.0 being installed via https://www.drupal.org/project/ignition. I don't see that at all.

Sorry for the noise, should have checked I was getting an up to date version.

**Comment by joachim-n** [comment]
Ah, and I filed this in the wrong project -- it should be in spatie/ignition, not spatie/laravel-ignition.
