### ISSUE TITLE
Laravel 11 error stack trace missing

### ISSUE THREAD

**Issue by mirzahaseebbaig** [spatie/laravel-ignition#208]
I'm not able to get the pencil icon on error page to move on my IDE, also the settings icon also not visible. 

![image](https://github.com/user-attachments/assets/d3c3d454-a54e-40ae-a149-c0fb1d89ffd3)

**Comment by rodrigopedra** [comment]
That is not ignition's error page.

Ignition is not shipped by default anymore, starting in Laravel 11.

The Laravel built-in error page resembles it, but has a more constrained feature set.

You can install ignition on your project by using:

```bash
composer require --dev spatie/laravel-ignition
```

**Comment by mirzahaseebbaig** [comment]
> That is not ignition's error page.
> 
> Ignition is not shipped by default anymore, starting in Laravel 11.
> 
> The Laravel built-in error page resembles it, but has a more constrained feature set.
> 
> You can install ignition on your project by using:
> 
> ```shell
> composer require --dev spatie/laravel-ignition
> ```

It's working, thanks @rodrigopedra
