### ISSUE TITLE
White flash when using dark design on LiveWire errors

### ISSUE THREAD

**Issue by hebbet** [spatie/laravel-ignition#26]
when using dark theme the error message is (sometimes) loaded in light/white first and then gets repainted.
That causes a "flash" of the screen

**Comment by hebbet** [comment]
that is still happening when the error message is loaded via an iframe, eg. on livewire errors.

**Comment by AlexVanderbist** [comment]
Hi @hebbet, can you try pulling in the latest version of laravel-ignition (running `composer update` should be enough)? We've moved the darkmode script to the head part of the page so it should load slightly faster.

**Comment by hebbet** [comment]
yes, but it is still flashing.

**Comment by AlexVanderbist** [comment]
Hi @hebbet, finally got around to further investigating this issue. As of yesterday (spatie/ignition 1.2.9) it should've been fixed. Thanks for your patience and reporting this issue :)
