### ISSUE TITLE
Tweak to the Laravel 8 Install Doc

### ISSUE THREAD

**Issue by 2h4services** [spatie/laravel-ignition#31]
In the docs for Laravel 8 you have to swap out the composer dependency
![Screenshot_20220128_084934](https://user-images.githubusercontent.com/98058142/151587982-74c8be58-d2be-4cec-8943-a7f097b438c8.png)

However, Laravel 8 out of the box has the old Ignition as around 2.5
```
"facade/ignition": "^2.5",
```
Whereas this version is around ^1.0.  This will cause a composer error if you just change the name.

So just to make it more clear you might want to add something that shows swapping that
```
"spatie/laravel-ignition": "^1.0"
```

**Comment by AlexVanderbist** [comment]
Thanks for the suggestion! We've added a bit more information (should appear later today).
