### ISSUE TITLE
Laravel Debugbar issue

### ISSUE THREAD

**Issue by tanthammar** [spatie/laravel-ignition#32]
"spatie/laravel-ignition": "1.0.2",
PHP 8.1.2
Laravel 8.81.0
"barryvdh/laravel-debugbar": "3.6.6",

Most of the time when I get an error, it is not displayed because It gets stuck with the Laravel debugbar.
```ci
Cannot assign Barryvdh\Debugbar\DebugbarViewEngine to property Spatie\LaravelIgnition\Views\ViewExceptionMapper::$compilerEngine of type Illuminate\View\Engines\CompilerEngine
```

Example:
https://flareapp.io/share/87nzGkd7#F55

**Comment by rrpadilla** [comment]
Having the same issue:
- Laravel: 9.0.0
- PHP 8.1.2

**Comment by freekmurze** [comment]
Does the error go away if you remove the typehint on this line
https://flareapp.io/share/87nzGkd7#F55L21  ?

**Comment by freekmurze** [comment]
This should work in the latest release. If not, open up a new issue.
