### ISSUE TITLE
Some exceptions return a default symfony exception

### ISSUE THREAD

**Issue by ReeceM** [spatie/laravel-ignition#33]
## Versions
- Laravel version `8.81.0`
- PHP version `8.0.14`
- spatie/laravel-ignition `^1.0`

## Description 

When some errors occur with the 'spatie/laravel-ignition^1.0` package the default symfony exception occurs, however  the `facade/ignition` package this returns the Ignition error page for the same error. This was tested by downgrading and revisiting the same page.

I discovered when using the Resources in my application. When inside the `toArray` method I called an undefined function it threw the default symfony page, not the ignition page.

But when I call the same undefined function in say the `web.php` file it returns the ignition error page correctly.

## Observation
I did dig through the code and also the stack trace as the code trace shows the exception hitting the ignition package and the renderer. Calls the ignition error page and such. Then ends up showing the old error page. (not sure if it has to do with the re-throwing of the exception as because of the Error issue?)

But it does appear the issue does maybe originate within the `IgnitionWhoopsHandler::class` ? The section that catches the `Error` class and throws a new `ErrorException`.

I found by remove all of that and using just the render code it works alright. Is this because of being for Laravel 9?

## Reproduction 
I created a reproduction repository to show the error.

[https://github.com/ReeceM/ignition-error-repo](https://github.com/ReeceM/ignition-error-repo)

It has the following routes: 

### Key

✅ - Shows correct error page
❌ - shows symfony page

| url | result | info |
|----| -----| --- |
| [127.0.0.1:8000/with-default-resource](http://127.0.0.1:8000/with-default-resource) | ✅ | doesn't use `toArray` |
| [127.0.0.1:8000/without-inertia](http://127.0.0.1:8000/without-inertia) | ✅ | Just uses the function in routes file |
| [127.0.0.1:8000/](http://127.0.0.1:8000/)  |  ❌ | this calls a `UserResource` and function is in `toArray` |
| [127.0.0.1:8000/with-json](http://127.0.0.1:8000/with-resource) | ❌ | anonymous JsonResource class with `toArray` defined |
| [127.0.0.1:8000/with-model](http://127.0.0.1:8000/with-model) |❌ | the model has a custom `toArray` method |
| [127.0.0.1:8000/with-model-json](http://127.0.0.1:8000/with-model-json) | ✅ | this uses the torsion method to cast |

**Comment by AlexVanderbist** [comment]
Hi @ReeceM, thanks for the detailed explanation! I'll look into this asap, hopefully even this weekend.

**Comment by ReeceM** [comment]
> Hi @ReeceM, thanks for the detailed explanation! I'll look into this asap, hopefully even this weekend.

Thanks @AlexVanderbist for having a look 👍
