### ISSUE TITLE
Error Page is not rendering CSS.

### ISSUE THREAD

**Issue by whobutsb** [spatie/laravel-ignition#35]
Hello there!  I just updated a Laravel 8 application to Laravel 9.  In my composer.json I updated: 
`"facade/ignition": "^2.5"` to `"spatie/laravel-ignition": "^1.0"`

I then ran `composer update`.  In a sample route file: I manually threw an exception with `throw new \Exception('testing')`.  
The error page that get rendered shows the content but the CSS is not being loaded.  I have included a image at the bottom. 
Is there something I'm missing or an additional composer command I need to run? 

Thank you for the assistance. 

<img width="1392" alt="Screen Shot 2022-02-10 at 8 04 27 AM" src="https://user-images.githubusercontent.com/868190/153435574-048e0da1-d911-4adb-83a8-7e7c42043a7f.png">

**Comment by whobutsb** [comment]
Please ignore this issue I was able to throw another exception and the beautiful error pages are now showing up as expected.

**Comment by spartyboy** [comment]
same happening to me and its unfixable

**Comment by spartyboy** [comment]
No am using laravel debugbar

**Comment by spartyboy** [comment]
I feel its an issue the previous ignition works well with no glitch

**Comment by evtukhov** [comment]
![Screen Shot 2022-02-13 at 01 25 33](https://user-images.githubusercontent.com/11804586/153730782-27299297-4c68-4359-84c2-83530bd76d33.png)

The same on Mac OS X in Chrome latest version. spatie/laravel-ignition: 1.0.4

**Comment by jez500** [comment]
I'm getting the same thing, I have clockwork installed but uninstalled it and the same thing occurs. Seems to only be with 500 errors as something less significant like an undefined variable shows ignition.

Did a bit of debugging but unsure of expected behaviour. eg should ignition disable symfony/error-handler as they appear to do the same thing? Looks like symfony error-handler is getting in beforehand causing its output to get dumped in the script tag

Started happening after upgrade from laravel 8 to 9 and changing `facade/iginition` to `spatie/laravel-ignition`. Tested versions 1.0.4 and 1.0.6

When it's working it looks top-notch! :)

**Comment by goaround** [comment]
Check if you really run PHP 8.1. That was my mistake.

**Comment by jez500** [comment]
Yeah, 8.1.1

```
$ php --version
PHP 8.1.1 (cli) (built: Dec 18 2021 02:01:00) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies
```

**Comment by freekmurze** [comment]
@jez500 have you check the version of PHP you're using for web requests? http://freek.dev/php-version

**Comment by grantholle** [comment]
For me, the html is malformed:

```html
<!DOCTYPE html>
<html lang="en" class="auto">
<!--
[stacktrace was here]
-->
<head>
    <!-- Hide dumps asap -->
    <style>
        pre.sf-dump {
            display: none !important;
        }
    </style>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="robots" content="noindex, nofollow">

    <title>Undefined property: App\Models\UserGame::$score</title>

</head>
<body class="scrollbar-lg">

<script>
    window.data = <!-- Undefined property: App\Models\UserGame::$score (500 Internal Server Error) -->
<!DOCTYPE html>
<html lang="en">
```

**Comment by spartyboy** [comment]
> For me, the html is malformed:
> 
> ```
> <!DOCTYPE html>
> <html lang="en" class="auto">
> 
> <head>
>     
>     <style>
>         pre.sf-dump {
>             display: none !important;
>         }
>     </style>
> 
>     <meta charset="UTF-8">
>     <meta name="viewport" content="width=device-width, initial-scale=1.0">
>     <meta http-equiv="X-UA-Compatible" content="ie=edge">
>     <meta name="robots" content="noindex, nofollow">
> 
>     <title>Undefined property: App\Models\UserGame::$score</title>
> 
> </head>
> <body class="scrollbar-lg">
> 
> <script>
>     window.data = 
> <!DOCTYPE html>
> <html lang="en">
> ```

This exactly is what i feel is the cause it opens a new html tag in a previously opened one

**Comment by freekmurze** [comment]
In the exceptions that I throw, the HTML of the Ignition page is valid. 

Could you create a minimal Laravel app where you recreate the issue?

**Comment by grantholle** [comment]
I wish I could. I've upgraded two projects to Laravel 9. One (with the most dependencies and complexity) is rendering fine, the other (much simpler) will not render.

When starting a new project with the same `composer.json` file, it works as expected. I'm going to keep tinkering, but I really can't pinpoint what's the deal.

**Comment by grantholle** [comment]
Just doing some searching around, I think @jez500 was on to it:

> Did a bit of debugging but unsure of expected behaviour. eg should ignition disable symfony/error-handler as they appear to do the same thing? Looks like symfony error-handler is getting in beforehand causing its output to get dumped in the script tag

It looks like Symfony's error handler HTML page is getting included in the output [here](https://github.com/spatie/ignition/blob/main/resources/views/errorPage.php#L27).

**Comment by moisish** [comment]
I think I found where the Symfony's error html page is included 

https://github.com/spatie/ignition/issues/48#issuecomment-1050695607

**Comment by AlexVanderbist** [comment]
Hey all, a fix has been tagged [here](https://github.com/spatie/flare-client-php/releases/tag/1.0.3). Running `composer update` on your projects will automatically pull this in. Please let me know if this fixes your issues :)

**Comment by whobutsb** [comment]
> 

Amazing, thank you so much for fixing this.  Just checked out a random variable in my blade template and it is now showing the correct error page.

**Comment by jez500** [comment]
Awesome, thank you!
