### ISSUE TITLE
Bug with ignition opening multiple html tags with php debugbar error

### ISSUE THREAD

**Issue by spartyboy** [spatie/laravel-ignition#37]
ignition shows symphony error with blank on v 1.0.4
![Screenshot (227)](https://user-images.githubusercontent.com/26467959/153595881-047dab66-0378-42ef-a59d-b2cc8ad330a3.png)
![Screenshot (228)](https://user-images.githubusercontent.com/26467959/153595885-dae88912-6cf9-4b4d-ad02-afa46c1478d9.png)
![Screenshot (229)](https://user-images.githubusercontent.com/26467959/153595889-7f144b58-e3a4-4d95-8c97-a6f7371c676d.png)
![Screenshot (230)](https://user-images.githubusercontent.com/26467959/153595896-87a7fbdf-2ad5-477f-a0fe-5c142af7ee56.png)
![Screenshot (231)](https://user-images.githubusercontent.com/26467959/153595902-9df3bc93-b493-42c7-ba3c-fb5f529035af.png)

**Comment by freekmurze** [comment]
That's a strange error, and I don't know if it's caused by ignition: we don't use jQuery.

**Comment by spartyboy** [comment]
I noticed the jQuery it's an issue with debugbar and when i failing due to the ignition error.
I disabled laravel debugbar but still that blank white symfony error kept showing and the jQuery error was gone

**Comment by evtukhov** [comment]
![Screen Shot 2022-02-13 at 01 25 33](https://user-images.githubusercontent.com/11804586/153730524-90f5d4d8-9f80-41dc-b7ed-e10bbb224596.png)
The same on Mac OS X in Chrome latest version.

**Comment by AlexVanderbist** [comment]
Hi @spartyboy, this error was fixed a couple weeks ago. You can update to the latest version of Ignition by running `composer update`. 

Should the problem pop up again for you, please do not hesitate to open a new issue and tag me in it :)
