### ISSUE TITLE
Typo in Documentation (Writing Custom Middleware)

### ISSUE THREAD

**Issue by alexandercrice** [spatie/laravel-ignition#41]
https://flareapp.io/docs/ignition-for-laravel/writing-custom-middleware

A use-statement in one of the code samples has the namespace `Spatke`, which I believe should be `Spatie`.

![image](https://user-images.githubusercontent.com/20804591/153683223-d5694d05-218e-458e-9ffe-0e4547b480f5.png)

**Comment by freekmurze** [comment]
Fixed. Thanks!
