### ISSUE TITLE
Git information should not fail

### ISSUE THREAD

**Issue by edcoreweb** [spatie/laravel-ignition#44]
![image](https://user-images.githubusercontent.com/9083523/154058821-823773d8-bd3f-459d-8993-48837e0e9e88.png)

I think that it should not critically fail because of git, also 60 sec timeout seems a bit much.
What's your opinion on this?

This happens because I run the project from a NFS share, and there are a lot of files.
Ideally I can live without git information if it causes a long waiting time and or crashes.

**Comment by freekmurze** [comment]
This has been fixed in the latest version.
