### ISSUE TITLE
`IGNITION_SHARING_ENABLED=false` environment variable does not work

### ISSUE THREAD

**Issue by PaolaRuby** [spatie/laravel-ignition#46]
Does not work `IGNITION_SHARING_ENABLED=false`, share buttons are still showing,
![image](https://user-images.githubusercontent.com/79208489/154150691-c66830e6-c936-4875-bc0d-5de365eeb6b7.png)

 in "facade/ignition": "^2.5" everything is working

**Version:** 1.0.6
**Php:** 8.0/8.1
**Laravel:** 8.83/9.1

maybe related #21

**Comment by AlexVanderbist** [comment]
Hi @PaolaRuby, thanks for making us aware of this issue. I've got a fix ready to be tagged later today. You can pull in this fix using `composer update`.

**Comment by PaolaRuby** [comment]
It's working now, thanks
