### ISSUE TITLE
window.ignite is not a function

### ISSUE THREAD

**Issue by ankheur** [spatie/laravel-ignition#49]
I'm developping a laravel project with Metronic 8 theme
Since I upgraded to Laravel 9 from the last version of Laravel 8, when I get an error I have an empty page with errors on the console.

First an 
`Uncaught SyntaxError: Unexpected token '{' `

Which is due to the last line of this block of code
```
* Validation function for `value` and `defaultValue`.
 */function checkSelectPropTypes(props){{checkControlledValueProps('select',props);for(var i=0;i<valuePropNames.length;i++){var propName=valuePropNames[i];if(props[propName]==null){continue;}var isArray=Array.isArray(props[propName]);if(props.multiple&&!isArray){error('The `%s` prop supplied to <select> must be an array if '+'`multiple` is true.%s',propName,getDeclarationErrorAddendum());}else if(!props.multiple&&isArray){error('The `%s` prop supplied to <select> must be a scalar '+'value if `multiple` is false.%s',propName,getDeclarationErrorAddendum());}}}}function updateOptions(node,multiple,propValue,setDefaultSelected){var options=node.options;if(multiple){var selectedValues=propValue;var selectedValue={};for(var i=0;i<selectedValues.length;i++){// Prefix to avoid chaos with special keys.
selectedValue['$'+selectedValues[i]]=true;}for(var _i=0;_i<options.length;_i++){var selected {// Do not set `select.value` as exact behavior isn't consistent across all
```
and an error 
`window.ignite is not a function`

When I remove the package from my project, I get the default symfony error page without problem. Did I miss something when I installed the laravel-ignition package ? 

Version: 1.0.6
Php: 8.0.6
Laravel: 9.1

**Comment by AlexVanderbist** [comment]
Hi @ankheur, can you try to replicate the issue again on the latest version of laravel-ignition (1.0.6) and its dependencies? You'll probably need to run `composer update` to pull in any changes to the underlying `spatie/ignition` package.

Thanks!

**Comment by ankheur** [comment]
Hi ! The issue seemed to have come from a dependency problem from the Metronic package and an update from them resolved the issue. Thanks and sorry for this thread
