### ISSUE TITLE
Runnable solutions don't get their execute_endpoint anymore

### ISSUE THREAD

**Issue by AdrianMrn** [spatie/laravel-ignition#5]
It looks like `spatie/ignition` is still trying to create an endpoint to execute the solution with a controller that doesn't exist anymore (it does exist in `spatie/laravel-ignition` though):

https://github.com/spatie/ignition/blob/main/src/Solutions/SolutionTransformer.php#L6

This causes a couple of properties to be missing from the solutions. This is what I get:

```JS
{
    class: 'Spatie\\LaravelIgnition\\Solutions\\GenerateAppKeySolution',
    title: 'Your app key is missing',
    description: '',
    links: { 'Laravel installation': 'https://laravel.com/docs/master/installation#configuration' },
    action_description: 'Generate your application encryption key using `php artisan key:generate`.',
    is_runnable: true,
}
```

I expect to also see `run_button_text`, `run_parameters` and `execute_endpoint`. When an error is created in ignition and doesn't pass through laravel-ignition, `is_runnable` should be false.

**Comment by freekmurze** [comment]
Fixed!
