### ISSUE TITLE
Send shareable error report to front

### ISSUE THREAD

**Issue by AdrianMrn** [spatie/laravel-ignition#6]
As agreed in the call from last week (or maybe 2 weeks ago?), we'll still create the shareable error report in the backend and append this to the end of the ignition HTML.

This will ensure that the ignition page can still be rendered as fast as possible, and that we don't have to copy over all the stripping logic to JS.

You can just add it as a comment in the blade here, and I'll make sure it finds its way to the share component in React 👍 
https://github.com/spatie/ignition/blob/68a6b91eb7e2592239a552dfb85768a8b1a2c925/resources/views/errorPage.php#L50

**Comment by freekmurze** [comment]
Added it as `shareableReport` in `window.data` 👍
