### ISSUE TITLE
Error page does not work

### ISSUE THREAD

**Issue by imithu** [spatie/laravel-ignition#64]
- Laravel Version: 9.2.0
- PHP Version: 8.1.3
- Database Driver & Version: N\A

### Description:
Ignition html error page does not work in both Insomnia preview mode and thunder client preview mode.
It works only in browser.

### Steps To Reproduce:
I have created a live endpoint so that you can understand the issue.
```https://insomnia-open-source.imithu.org/api/test```
open this endpoint in,
- any latest browser
- insomnia

I hope, you have found the error.

### Relation
- [Insomnia Issue 4522](https://github.com/Kong/insomnia/issues/4522)
- [Laravel Issue 41266](https://github.com/laravel/framework/issues/41266)

**Comment by imithu** [comment]
# Modern Browser
![modern browser](https://user-images.githubusercontent.com/76824197/155878708-f44f2019-4960-43f2-b203-76410897222b.png)

# Insomnia
![insomnia](https://user-images.githubusercontent.com/76824197/155878710-a40f1e77-cd5b-41be-a52d-eb52f4a53133.png)

# Thunder Client (vs code extension)
![Thunder Client](https://user-images.githubusercontent.com/76824197/155904347-80bb6aff-babd-4cf9-98e6-42096be2c0ed.png)




good luck

**Comment by anyforever** [comment]
How to solve it?
@imithu

**Comment by imithu** [comment]
updating insomnia and spatie/laravel-ignition worked for me.
i hope only updating spatie/laravel-ignition will solve ur problem.

**Comment by anyforever** [comment]
@imithu Thank u very much!

**Comment by imithu** [comment]
> @imithu Thank u very much!

Alhamdulillah (all the praises and thanks be to ALLAH)

**Comment by kedniko** [comment]
⚡ In my case I had to disable `barryvdh/laravel-debugbar`

👉 Add this to `app/Providers/AppServiceProvider.php` -> register()
```
if (strpos(Request::userAgent(), 'insomnia') !== false) {
    Debugbar::disable();
}
```

**Comment by h-zone** [comment]
i experiencing same issue
