### ISSUE TITLE
Runnable Solutions not working in upgraded Legacy-Laravel Apps because of `$namespace`

### ISSUE THREAD

**Issue by jonas-kell** [spatie/laravel-ignition#67]
My company has a Laravel app that was created around the 4.x/5.0 stage of Laravel.

The upgrades have always been performed correctly according to the upgrade-guides.

However I noticed, runnable solutions weren't working in this application, while they were in the new ones I created.

After digging for quite a while, I realized, this was due to the (in 9.x no longer existent) `$namespace` property of `App\Providers\RouteServiceProvider`. 
Having this set, causes a silently caught Exception in `Spatie\LaravelIgnition\Solutions\SolutionTransformers\LaravelSolutionTransformer::executeEndpoint` because it tries to construct a Laravel-Controller from `Spatie\LaravelIgnition\Http\Controllers\ExecuteSolutionController`.

But if the `$namespace` is e.g. set to `protected $namespace = 'App\Http\Controllers'`; it tries to construct the Controller `App\Http\Controllers\Spatie\LaravelIgnition\Http\Controllers\ExecuteSolutionController`. This one doesn't exist for obvious reasons.

I'm no expert in constructing Laravel-Controllers in packages, if it is maybe possible to ignore the Namespace-overwrite in a package (would make sense, but I couldn't find an option to force the $namespace to be ignored).

If this can be fixed without too much work this is obviously preferable, otherwise this needs to definitely be mentioned in the Installation steps for this package in apps apart from default Laravel instances. It isn't even that hard to work around some old applications [LIKE HERE](https://github.com/laravel/framework/issues/9206), if you are aware of it.

**Comment by AlexVanderbist** [comment]
Hi @jonas-kell,

Thanks for bringing this to our attention! I've tagged a fix in v1.0.7. Running `composer update` will automatically pull this fixed version in 👍
