### ISSUE TITLE
SQL error should close only with collapse icon.

### ISSUE THREAD

**Issue by eusonlito** [spatie/laravel-ignition#73]
* Version: 1.0.10
* Laravel: 9.5

When a SQL error occurs, some times I want to copy only a part of SQL query or simply select some part to hightlight and focus on it, but every time that a click is made on SQL query, the layer collapse.

I think that is better to open the error with a click on any layer part, but to close is a better option to close only using the collapse icon.

Copy all SQL with the copy button and paste after in a editor is almost always slow than select some SQL chunks directly from ignition.

Thanks!

**Comment by AlexVanderbist** [comment]
Hi @eusonlito, great idea. I've tried to select, and accidentally collapsed the SQL fields too many times. If you, or anyone else feels up to the challenge, feel free to open a PR! Otherwise, I might look into it later :)

I'll leave this open for visibility!

**Comment by AlexVanderbist** [comment]
bad bot
