### ISSUE TITLE
Large SQL lines are not visible on SQL error panel

### ISSUE THREAD

**Issue by eusonlito** [spatie/laravel-ignition#74]
* Version: 1.0.10
* Laravel: 9.5

I have some SQL queries with large table names and columns and when a error occurs, the SQL is not fully visible on the right.

![Screenshot from 2022-03-17 18-47-27](https://user-images.githubusercontent.com/644551/158864119-5b678b24-c903-4838-9946-1d94c95dbef2.png)

Maybe adding a `overflow: auto` to layer?

Thanks!

**Comment by AlexVanderbist** [comment]
Hi @eusonlito, are you talking about not being able to horizontally scroll to the right, or is the end of the string getting hidden behind the fade-out?

**Comment by eusonlito** [comment]
@AlexVanderbist yes, there aren't horizontal scroll, then large SQL lines are hidden behind the fade out :)

**Comment by eusonlito** [comment]
I finally removed all solution providers and all my problems gone away 😅

**Comment by AlexVanderbist** [comment]
bad bot
