### ISSUE TITLE
Console warning when throwing test exception 

### ISSUE THREAD

**Issue by tomshaw** [spatie/laravel-ignition#88]
After upgrading from Laravel 8 to 9 I'm getting a console warning when throwing a test exception.

- Laravel Version: 9.0
- PHP Version: 8.0.10/8.1.2
- Ignition Version: spatie/laravel-ignition 1.0
```

admin:215 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Xc`. See https://reactjs.org/link/warning-keys for more information.
    at Xc (http://mysite.local/admin:215:581601)
    at Jc (http://mysite.local/admin:215:583586)
    at div
    at es (http://mysite.local/admin:215:538133)
    at div
    at $c (http://mysite.local/admin:215:580128)
    at es (http://mysite.local/admin:215:538133)
    at Zc (http://mysite.local/admin:215:584093)
    at section
    at rm (http://mysite.local/admin:215:660887)
    at main
    at ye (http://mysite.local/admin:215:307426)
    at Ie (http://mysite.local/admin:215:308955)
    at es (http://mysite.local/admin:215:538133)
    at om (http://mysite.local/admin:215:662493)
```

**Comment by AlexVanderbist** [comment]
Hi @tomshaw, can you try updating the `spatie/laravel-ignition` package and its dependencies to its latest version?

You can do so using following command: 

```
composer update spatie/laravel-ignition -W
```

**Comment by tomshaw** [comment]
@AlexVanderbist Composer updated `spatie/laravel-ignition` `spatie/ignition (1.2.7 => 1.2.9)` perfectly unfortunately the same console error message persists. I'm using Livewire also not using tailwind but company theme, I'm not sure if that makes a difference. Oddly enough it's just a common React iteration error.  Thanks 👍

**Comment by AlexVanderbist** [comment]
Hi again @tomshaw, you're right about it being a common React warning. It definitely won't affect the Ignition error page at all. So nothing to worry about.

We're always working on improving Ignition and we come across the missing keys quite often. I'm sure we'll have it fixed in one of the next versions. In case you (or anyone else reading this thread) have a concrete example where this goes wrong; feel free to PR a fix to https://github.com/spatie/ignition-ui.

Thanks!

**Comment by tomshaw** [comment]
@AlexVanderbist Functionality speaking it may not have any effect. Professionally speaking it fails. Consider updating your build process.

Thanks
