### ISSUE TITLE
Class LogMessage not found

### ISSUE THREAD

**Issue by dejagersh** [spatie/laravel-ignition#89]
I keep getting the following error:

```
Class \"Spatie\\LaravelIgnition\\Recorders\\LogRecorder\\LogMessage\" not found
```

in the file `spatie/laravel-ignition/src/Recorders/LogRecorder/LogRecorder.php`

I suspect this is similar to: https://github.com/spatie/laravel-ray/issues/237

I "solve" it by putting `opcache_reset()` in `public/index.php`

**Comment by michael-rubel** [comment]
The problem still persists. It works at the process start but crashes after some time working.
Composer version: `2.3.10`

Ping @freekmurze

**Comment by s-fog** [comment]
Have same problem. Any help? :)
