### ISSUE TITLE
Collapse, Save and Edit don't work

### ISSUE THREAD

**Issue by rudynac** [spatie/laravel-ignition#93]
In the debug page of spatie/ignition (version 1.2.3, the latest) the following operations do not work:
- the "collapse vendor frames" button
- saving the settings (top right)
- opening the editor

https://user-images.githubusercontent.com/12033555/170677233-00b8a03a-4680-44d0-9395-d81471ded5fa.png

Specs:
Windows 11
Chrome, Firefox, Edge
Laravel 9
PHP 8.1.2

**Comment by warmwhisky** [comment]
I've never got the editor "PHPStorm" to open.  I've tried on Windows 10, Mint and Ubuntu. Seems to be no documentation regarding making this work either.
